baseURL = 'https://www.sketchandblog.com/'
languageCode = 'en-us'
title = 'Sketch and Blog'
theme = "Ananke"

[params]
  text_color = "navy"
  author = "Karol Bajrulewicz"
  #favicon = ""
  #site_logo = ""
  description = "Blog about art and life."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/sketch-and-blog-light.jpg"
  recent_posts_number = 2
